
import type { Metadata } from "next";
import "./globals.css"
import Header from "@/app/Header_Main";
import Footer from "@/app/Footer_Main";

export const metadata: Metadata = {
  title: 'ReVOLT',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
      </head>
      <body>
        <Header/>{children}<Footer/>
      </body>
    </html>
  )
}
