
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import "./globals.css"
import header_styles from "@/styles/Header.module.css";
import footer_styles from "@/styles/Footer.module.css";
import "@/app/header_sidebar";
import SidebarComponent from "@/app/header_sidebar";

export const metadata: Metadata = {
  title: 'ReVOLT',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
      </head>
      <body>
        <Header/>{children}<Footer/>
      </body>
    </html>
  )
}

export function Header() {
  return (
    <header id={header_styles.header}>
      <div id={header_styles.header_image}>
        <Image 
          src="/revolt_logo.png"
          alt="ReVOLT Logo"
          width={200}
          height={50}
        />
      </div>

      <div id={header_styles.header_menu}>
        <Link id={header_styles.header_buttons} href="/">Home</Link>
        <Link id={header_styles.header_buttons} href="/projects">Projects</Link>
        <Link id={header_styles.header_buttons} href="/timeline">Timeline</Link>
        <Link id={header_styles.header_buttons} href="/sponsors">Sponsors</Link>
        <Link id={header_styles.header_buttons} href="/team">Team</Link>
      </div>
        
      <div id={header_styles.header_sidebar}>
        <SidebarComponent />
      </div>

    </header>
  );
}

function Footer() {
  return (
    <footer id={footer_styles.footer}>
      <p id={footer_styles.footer}>Footer</p>
    </footer>
  );
}
